version: '3'
services:

  frontend.public:
    build:
      dockerfile: Dockerfile
      context: ./frontend/public
    container_name: frontend.public
    volumes:
      - ./frontend/public/src:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    depends_on:
      - laravel.api
      - laravel.jobs.avatars
    networks:
      - s_net

  laravel.api:
    build:
      dockerfile: Dockerfile_api
      context: ./backend/api
    container_name: laravel.api
    volumes:
      - ./backend/api/src:/var/www/html
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db.mysql.main
      - db.redis.cache
    networks:
      - s_net

  laravel.jobs.avatars:
    build:
      dockerfile: Dockerfile_avatars
      context: ./backend/api
    container_name: laravel.jobs.avatars
    volumes:
      - ./backend/api/src:/var/www/html
    env_file:
      - .env
    depends_on:
      - db.mysql.main
      - db.redis.cache
      - db.redis.jobs
    networks:
      - s_net


  db.mysql.main:
    build:
      dockerfile: Dockerfile
      context: ./services/mysql
    container_name: db.mysql.main
    volumes:
      - ./volumes/db/mysql/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - s_net

  db.redis.cache:
    build:
      dockerfile: Dockerfile
      context: ./services/redis
    container_name: db.redis.cache
    volumes:
      - ./volumes/db/redis/cache:/data
    networks:
      - s_net

  db.redis.jobs:
    build:
      dockerfile: Dockerfile
      context: ./services/redis
    container_name: db.redis.jobs
    volumes:
      - ./volumes/db/redis/jobs:/data
    networks:
      - s_net

  db.redis.socket.connections:
    build:
      dockerfile: Dockerfile
      context: ./services/redis
    container_name: db.redis.socket.connections
    volumes:
      - ./volumes/db/redis/socket_connections:/data
    networks:
      - s_net

  socket.1:
    build:
      dockerfile: Dockerfile
      context: backend/socket_server
    container_name: socket.1
    volumes:
      - ./backend/socket_server/src:/usr/src/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=socket_1
      - SERVER_PORT=3000
    depends_on:
      - laravel.api
      - laravel.jobs.avatars
      - db.redis.socket.connections
    networks:
      - s_net

  nginx.router:
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - laravel.api
      - db.mysql.main
      - db.redis.cache
    networks:
      - s_net

networks:
  s_net:
    driver: bridge