openapi: 3.0.0
info:
  title: 'Social Network'
  description: '## An attempt to implement a social network with basic functionality using "Laravel 10" for backend and "React Framework" for frontend.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
    description: 'Local API server'
paths:
  /api/auth/login:
    post:
      tags:
        - auth
      summary: 'Login a user'
      operationId: api.auth.login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 'User logged in successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessLoginResource'
        '401':
          description: 'Unauthorized attempt to get access'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: failure }
                  message: { type: string, example: Unauthorized }
                type: object
        '422':
          description: 'Validation errors occurred'
          content:
            application/json:
              schema:
                properties:
                  errors: { properties: { email: { type: array, items: { type: string, example: 'The email has already been taken.' } }, password: { type: array, items: { type: string, example: 'The password field is required.' } } }, type: object }
                type: object
        '500':
          description: 'Some internal server error occurred'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResource'
  /api/auth/logout:
    get:
      tags:
        - auth
      summary: 'Perform logout for user'
      operationId: api.auth.logout
      requestBody:
        required: false
      responses:
        '200':
          description: 'User successfully logged out'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: success }
                  message: { type: string, example: 'User successfully logged out' }
                type: object
        '500':
          description: 'Some internal server error occurred'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResource'
  /api/auth/profile:
    get:
      tags:
        - auth
      summary: 'Get a user profile'
      operationId: api.auth.profile
      requestBody:
        required: false
      responses:
        '200':
          description: 'Profile data extracted successfully'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: success }
                  message: { type: string, example: 'Profile data extracted successfully' }
                  user: { $ref: '#/components/schemas/User' }
                type: object
        '500':
          description: 'Some internal server error occurred'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResource'
  /api/auth/register:
    post:
      tags:
        - auth
      summary: 'Register a user'
      operationId: api.auth.register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: 'Registration was successful'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessRegisterResource'
        '400':
          description: "The passwords don't match"
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: failure }
                  message: { type: string, example: "The passwords don't match" }
                type: object
        '401':
          description: 'Something went wrong while creating token for user'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: failure }
                  message: { type: string, example: 'Something went wrong while creating token for user' }
                type: object
        '422':
          description: 'Validation errors occurred'
          content:
            application/json:
              schema:
                properties:
                  errors: { properties: { first_name: { type: array, items: { type: string, example: 'The first name field is required.' } }, last_name: { type: array, items: { type: string, example: 'The last name field is required.' } }, email: { type: array, items: { type: string, example: 'The email has already been taken.' } }, username: { type: array, items: { type: string, example: 'The username has already been taken.' } }, password: { type: array, items: { type: string, example: 'The password field is required.' } }, password_confirmation: { type: array, items: { type: string, example: 'The password confirmation field is required.' } } }, type: object }
                type: object
        '500':
          description: 'Some internal server error occurred'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResource'
  /api/profile/avatar:
    post:
      tags:
        - profile
      summary: "Upload user's avatar"
      operationId: api.profile.avatar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadUserAvatarRequest'
      responses:
        '200':
          description: "Uploading of user's avatar went successfully"
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: success }
                  message: { type: string, example: 'Avatar was uploaded successfully' }
                type: object
        '401':
          description: 'Unauthorized attempt to get access'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: failure }
                  message: { type: string, example: Unauthorized }
                type: object
        '422':
          description: 'Validation errors occurred'
          content:
            application/json:
              schema:
                properties:
                  errors: { properties: { avatar: { type: array, items: { type: string, example: 'The avatar field is required.' } } }, type: object }
                type: object
        '500':
          description: 'Some internal server error occurred'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResource'
components:
  schemas:
    ValidationError:
      properties:
        message:
          type: string
          example: 'The given data was invalid.'
        errors:
          properties:
            'key 1':
              type: array
              items:
                type: string
                example: 'Error message 1'
            'key 2':
              type: array
              items:
                type: string
                example: 'Error message 2'
          type: object
      type: object
    LoginRequest:
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: john@example.com
        password:
          type: string
          example: '123456'
      type: object
    RegisterRequest:
      required:
        - first_name
        - last_name
        - email
        - password
        - password_confirmation
      properties:
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: john@example.com
        username:
          type: string
          example: john_doe123
        password:
          type: string
          example: '123456'
        password_confirmation:
          type: string
          example: '123456'
      type: object
    UploadUserAvatarRequest:
      required:
        - avatar
      properties:
        avatar:
          description: 'The avatar image file to upload.'
          type: string
          format: binary
      type: object
    SuccessAuthResource:
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: '"Registration was successful" or "User logged in successfully"'
        user:
          $ref: '#/components/schemas/User'
        authorization:
          $ref: '#/components/schemas/TokenResource'
      type: object
    SuccessLoginResource:
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: 'User logged in successfully'
        user:
          $ref: '#/components/schemas/User'
        avatars:
          description: "Array of user's avatars. Original version of avatar can be null and also of various extension"
          example:
            - 'http://localhost/storage/avatars/1/large.webp'
            - 'http://localhost/storage/avatars/1/medium.webp'
            - 'http://localhost/storage/avatars/1/small.webp'
            - 'http://localhost/storage/avatars/1/original.jpg'
        authorization:
          $ref: '#/components/schemas/TokenResource'
      type: object
    SuccessRegisterResource:
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: 'Registration was successful'
        user:
          $ref: '#/components/schemas/User'
        authorization:
          $ref: '#/components/schemas/TokenResource'
      type: object
    TokenResource:
      properties:
        access_token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL3JlZ2lzdGVyIiwiaWF0IjoxNzA2NTUyMTM4LCJleHAiOjE3MDY5MTIxMzgsIm5iZiI6MTcwNjU1MjEzOCwianRpIjoiRk9hclkyZ2VvckhPT1llbSIsInN1YiI6IjQiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiZW1haWwiOiJ2YXN5YTJAdmFzeWEuY29tIiwibmFtZSI6InZhc3lhMiJ9.APeVTaT7gnkVVboKkfXDndq1vjQFiiaMPCw21aS9hL8
        type:
          type: string
          example: bearer
      type: object
    InternalServerErrorResource:
      properties:
        status:
          type: string
          example: failure
        message:
          type: string
          example: 'Internal server error'
      type: object
    User:
      properties:
        id:
          type: integer
          example: '2'
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: john@example.com
        username:
          type: string
          example: john_doe123
      type: object
  securitySchemes:
    BearerToken:
      type: http
      bearerFormat: JWT
      scheme: bearer
