openapi: 3.0.0
info:
  title: 'Social Network'
  description: '## An attempt to implement a social network with basic functionality using "Laravel 10" for backend and "React Framework" for frontend.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
    description: 'Local API server'
components:
  schemas:
    ValidationError:
      properties:
        message:
          type: string
          example: 'The given data was invalid.'
        errors:
          properties:
            'key 1':
              type: array
              items:
                type: string
                example: 'Error message 1'
            'key 2':
              type: array
              items:
                type: string
                example: 'Error message 2'
          type: object
      type: object
  securitySchemes:
    BearerToken:
      type: http
      bearerFormat: JWT
      scheme: bearer
